# Generated by Django 3.0.5 on 2020-04-12 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('slide_photo_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('slide_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('slide_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('slide_photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('slide_photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='flattype',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 16, 9, 11, 410213)),
        ),
    ]
