# Generated by Django 3.0.5 on 2020-05-05 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_auto_20200412_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flattype',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='dining_hall',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='isometric_view',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='list_date',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='photo_main',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='sqft',
        ),
        migrations.CreateModel(
            name='FlatTypeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqft', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.IntegerField()),
                ('dining_hall', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('isometric_view', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('floor_plan', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 6, 0, 55, 45, 935756))),
                ('flat_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.FlatType')),
            ],
        ),
    ]
