# Generated by Django 3.0.5 on 2020-05-12 08:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_auto_20200512_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=100)),
                ('floor_num_start', models.IntegerField()),
                ('floor_num_end', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='flattypedetail',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 12, 14, 11, 41, 492498)),
        ),
        migrations.CreateModel(
            name='FloorRangeAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.BlockType')),
            ],
        ),
    ]
