# Generated by Django 3.0.5 on 2020-05-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_auto_20200512_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flattypedetail',
            name='list_date',
        ),
    ]
