# Generated by Django 3.0.5 on 2020-05-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_remove_flattypedetail_list_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitFlats',
            new_name='UnitFlat',
        ),
    ]
