# Generated by Django 3.0.5 on 2020-05-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_blockbaseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flattype',
            name='flat_desc',
            field=models.TextField(blank=True),
        ),
    ]
