# Generated by Django 3.0.5 on 2020-05-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_flattype_flat_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flattypedetail',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
