# Generated by Django 3.0.5 on 2020-05-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0013_auto_20200513_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flattypedetail',
            old_name='flat_type_desc',
            new_name='flat_type',
        ),
        migrations.AlterUniqueTogether(
            name='flattypedetail',
            unique_together={('flat_type', 'sqft')},
        ),
    ]
