# Generated by Django 3.0.5 on 2020-05-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0014_auto_20200513_2053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flattypedetail',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='flattypedetail',
            name='flat_type',
        ),
        migrations.RemoveField(
            model_name='unitflat',
            name='block_name',
        ),
        migrations.RemoveField(
            model_name='unitflat',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='unitflat',
            name='unit_flat_type',
        ),
        migrations.DeleteModel(
            name='BlockBaseImage',
        ),
        migrations.DeleteModel(
            name='FlatTypeDetail',
        ),
        migrations.DeleteModel(
            name='UnitFlat',
        ),
    ]
