# Generated by Django 3.0.5 on 2020-05-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0016_flattypedetail'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='flattypedetail',
            index_together={('flat_type', 'sqft')},
        ),
    ]
