# Generated by Django 3.0.5 on 2020-05-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0017_auto_20200516_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatTypeDetail',
        ),
    ]
