# Generated by Django 3.0.5 on 2020-05-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0019_flattypedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatTypeDetail',
        ),
    ]
