# Generated by Django 3.0.5 on 2020-05-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0021_flattypedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatTypeDetail',
        ),
    ]
