# Generated by Django 3.0.5 on 2020-05-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0022_delete_flattypedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatTypeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqft', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.IntegerField(default=0)),
                ('dining_hall', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('isometric_view', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('floor_plan', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('flat_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.FlatType')),
            ],
            options={
                'unique_together': {('flat_type', 'sqft')},
                'index_together': {('flat_type', 'sqft')},
            },
        ),
        migrations.CreateModel(
            name='UnitFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('Facing', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('car_parking', models.BooleanField(default=True)),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.BlockType')),
                ('floor_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.FloorRangeAllocation')),
                ('unit_flat_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.FlatTypeDetail')),
            ],
        ),
        migrations.CreateModel(
            name='BlockBaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_flats', models.IntegerField()),
                ('block_flat_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.FlatTypeDetail')),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.BlockType')),
            ],
        ),
    ]
